name: Linux Kernel Build

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'repository path'
        required: true
        default: 'v9fs/linux'
        type: string
      ref:
        description: 'repository reference'
        required: true
        default: 'ericvh/for-next'
        type: string
      resultstag:
        description: 'how to tag results'
        default: 'ci'
        type: string
  workflow_call:
jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/v9fs/docker:latest
      options: -u root
    steps:
    - uses: actions/checkout@v3
      with:
        repository:  ${{ inputs.repo }} 
        ref: ${{ inputs.ref }}     
    - name: configure
      run: mkdir -p .build && make O=.build defconfig
    - name: make
      run: make -j16 O=.build
    - uses: actions/upload-artifact@v3
      with:
        name: kernel-image
        path: .build/arch/*/boot/*Image
        retention-days: 1
  test:
    needs: latency
    runs-on: self-hosted
    container:
      image: ghcr.io/v9fs/docker:latest
      options: -u root
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: kernel-image
        path: .build/arch/*/boot/*Image
    - name: link workspaces to scratch directory
      run: mkdir -p /workspaces && ln -s `pwd` /workspaces/linux
    - name: Test sweep
      run: |
        cd /home/v9fs-test/test
        git config --global --add safe.directory /home/v9fs-test/test
        git pull
        export REF=${{ input.ref }}-${{ input.resultstag }}
        ./test.bash short ci
    - name: Store Logs
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: /home/v9fs-test/test/logs
        retention-days: 7
  latency:
    needs: build
    runs-on: self-hosted
    container:
      image: ghcr.io/v9fs/docker:latest
      options: -u root
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: kernel-image
        path: .build/arch/*/boot/*Image
    - name: link workspaces to scratch directory
      run: mkdir -p /workspaces && ln -s `pwd` /workspaces/linux
    - name: Test sweep
      run: |
        cd /home/v9fs-test/test
        git config --global --add safe.directory /home/v9fs-test/test
        git pull
        ./test.bash short latency
        echo ${{ inputs.resultstag }} ${{ inputs.repo }} ${{ inputs.ref }} > /home/v9fs-test/test/logs/tag.txt
    - name: Store Logs
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: /home/v9fs-test/test/logs
        retention-days: 7
    - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
